== Migration Strategy – ICP Cluster migration
:toc:
:toc-placement!:


toc::[]

=== OpenShift Installation

To migrate from ICP to Openshift, the recommended approach is a blue-green
deployment where an Openshift cluster is created alongside an existing ICP
cluster, the workload is migrated from ICP to Openshift, load balancers or DNS
entries are updated to point clients at the new cluster, and the ICP cluster is
retired.

We highly recommend infrastructure automation to create new clusters for
Openshift. This provides the quickest path for new cluster creation. We have
published infrastructure automation templates for ICP on various cloud
platforms, for example:

https://github.com/ibm-cloud-architecture/terraform-icp-vmware

Terraform Examples for OpenShift will be published soon.

In scenarios where resources are limited, the approach involves draining and
removing under-utilized ICP worker nodes and using the capacity to build a small
Openshift control plane with a few workers. Depending on available capacity, an
Openshift cluster can start as a single master and scale up to three masters as
capacity is made available.

=== User Migration

ifndef::env-github[]

include::./migration/ldap_migration.adoc[LDAP Migration]

include::./migration/rbac_migration.adoc[RBAC Migration]

endif::[]

ifdef::env-github[]

* link:./migration/ldap_migration.adoc[LDAP Migration]

* link:./migration/rbac_migration.adoc[RBAC Migration]

endif::[]


=== Workload Migration

In this section we used a case study of migrating our cloud native reference
application BlueCompute that was running on ICP to Openshift.

https://github.com/ibm-cloud-architecture/refarch-cloudnative-kubernetes

ifndef::env-github[]

include::./migration/container_mod.adoc[Modifying Containers to run in Openshift]

include::./migration/container_scc.adoc[Running Containers using SecurityContextConstraints in Openshift]

endif::[]


ifdef::env-github[]

* link:./migration/container_mod.adoc[Modifying Containers to run in Openshift]

* link:./migration/container_scc.adoc[Running Containers using SecurityContextConstraints in Openshift]

endif::[]

=== DevOps and Developer toolchains

Generally, ICP was not opinionated on DevOps, and if the toolchain is outside of
the platform there is no reason for this to change when migrating to Openshift.

Openshift’s value proposition does include some developer productivity tools
such as Source-to-Image (S2I) and containerized Jenkins, as well as tech preview
and support for Openshift Pipelines and CodeReady Workspaces, but in a migration
scenario where we are migrating existing workload from ICP these are not
required to change. We can simply treat Openshift as another Kubernetes platform
we are deploying to.

ifndef::env-github[]
:leveloffset: +1

include::./migration/jenkins_migration.adoc[Jenkins Migration]

:leveloffset: 0 

endif::[]

ifdef::env-github[]

* link:./migration/jenkins_migration.adoc[Jenkins Migration]

endif::[]

==== Continuous Deployment and GitOps adoption

ifndef::env-github[]
:leveloffset: +1

include::./migration/cd_migration.adoc[CD Migration]

:leveloffset: 0 

endif::[]

ifdef::env-github[]

* link:./migration/cd_migration.adoc[CD Migration]

endif::[]

==== Migration of Kubernetes Artifacts
jj
ifndef::env-github[]
:leveloffset: +1

include::./migration/app_resource_migration.adoc[Application Resource Migration]

:leveloffset: 0 

endif::[]

ifdef::env-github[]

* link:./migration/app_resource_migration.adoc[Application Resource Migration]

endif::[]



==== Using a Backup/Restore approach using Velero

==== Converting PodSecurityPolicy to SecurityContextConstraints

==== NetworkPolicy migration

==== Application LoadBalancer cutover

=== Storage Migration

ifndef::env-github[]
:leveloffset: +1

include::./migration/storage.adoc[Storage Migration]

:leveloffset: 0 

endif::[]

ifdef::env-github[]

* link:./migration/storage.adoc[Storage Migration]

endif::[]



=== Platform Data Migration

==== Monitoring Data

==== Historical Log Data
